[routes]

####################
#     PRUEBAS      #
####################
GET /tailwind/@function = pruebas->tailwind_@function

GET /pruebas/comprime = pruebas->comprime
GET /pruebas/comentarios = pruebas->comentarios

POST /pruebas/comentar = pruebas->comentar

GET /pruebas/confirmacion_mail = pruebas->confirmacion_mail
POST /pruebas/confirmar_email = pruebas->confirmar_mail

;GET /pruebas/@action = pruebas->@action
;GET /pruebas/comprimir/@type = pruebas->comprimir

;GET /minify/@type = pruebas->comprimir_archivos

;POST /pruebas/regiones [ajax] = pruebas->ciudades