[GLOBALS]
DEBUG = 2

;UI = "ui/,app/pages/,compressed/,app/uploads/"
;UI="app/views/,compressed/,uploads/,recursos/"
UI="UI/,compressed/, recursos/"

AUTOLOAD="app/controllers/,app/models/,app/helpers/"
LOGS="logs/"


#BASE DE DATOS
;BD_DRIVER = sqlite:db/elcatalogo.sqlite
MariaDB.DRIVER = 'mysql:host=127.0.0.1;port=3306;dbname=elcatalogo'
MariaDB.USER = 'elcatalogo'
MariaDB.PASS = '123elcatalogo'


,'username','password'
UPLOADS= "uploads/"


#WEB_DEVELOPER
AUTOR.nombre="Andres Espinoza A"
AUTOR.mail="xxxx@xxx.xxx"


SALT= "elcatalogo_"

;[CONFIGS]
;config/rutas.ini = true

;##########################
; application settings

; prefix all your db table names to avoid conflict
; with other apps that are using the same database
;db_table_prefix = fblg_

; use 'md5' for PHP < 5.3.7 and 'bcrypt' for best security
;password_hash_engine = md5
;password_md5_salt = jK$N!Lx5

; 
[ASSETS]
;# if this is false, you need to manually put the group markers like
;# <!-- assets-head --> and <!-- assets-footer --> into your template
auto_include = false

;# be greedy and also fetch all <link>, <script> and <style> tags
greedy = false

;# add some filters to the file type renderer
filter.js = minify,combine
filter.css = minify,combine

;# a writable public path, where filters can put files (relative to webroot)
public_path = compressed/

;# add the mtime to the final resource URI, to aid in asset caching
timestamps = true
