[routes]
#     FRONTEND
GET / = Publico\Inicio->inicio
GET /home = Publico\Inicio->inicio
GET /salir = Privado\salir->inicio

GET /inicio/cargando = Publico\Inicio->cargando

GET /perfil/@idPerfil = Publico\Perfil->verPerfil
;GET /mostrar/perfil/@idPerfil = Publico\Perfil->verPerfil2
GET /cargar-comentarios = Publico\Perfil->cargar_comentarios

POST /api/comentar = Api->comentar
POST /api/me-gusta = Api->me_gusta
POST /actualizar-comentario/@id = Api->actualizar_comentario
POST /nuevo-comentario/@id = Api->nuevo_comentario



POST /regiones  = Publico\Inicio->comboCiudades
;POST /filtrar = Ajax->filtrar_ciudad
POST /filtrar = Ajax->filtrar


GET /login = Publico\Login->inicio
POST /login = Publico\Login->authenticate
GET /recuperar = Elcatalogo->en_construccion

GET /registro = Publico\Registro->inicio
POST /registro = Publico\Registro->procesar_registro

GET /validar = Publico\Registro->confirmar_mail

GET|POST /verificar = Publico\Registro->validar_mail


GET /contacto = Publico\Contacto->inicio


;GET /login = Publico\Login->login_user_2

GET /captcha = Elcatalogo->img_seguridad

GET /whatsapp/@id = Publico\Perfil->contacto

#API
GET /api/usuarios = Api->filtrar_usuarios
GET /api/comentarios/@idUserOrigen/@idUserDestino = Api->mi_comentario



GET /consulta/logueado = Elcatalogo->revisaSiConectado


;POST /filtrar_tags = Ajax->filtrar_tags
;POST /filtrar_tags = Ajax->tag_filtrar

;POST /votar_perfil = Ajax->perfil_megusta

GET /miniaturas = Elcatalogo->generar_todas_miniaturas



####################
#     USUARIO      #
####################
;GET /privado/inicio = Privado\User->inicio
;GET /privado/logout = Privado\Inicio->logout


GET /privado/{@controller} = Privado\{@controller}->inicio
GET /privado/{@controller}/{@action} = Privado\{@controller}->{@action}


;USER
POST /privado/user/actualizar = Privado\User->actualizar
;PERFIL
;GET /privado/perfil/@action = Privado\Perfil->@action
POST /privado/perfil/guardar = Privado\Perfil->guardar


;MEDIA
;GET /privado/media/@action = Privado\Media->@action
POST /privado/media/guardar = Privado\Media->subir_archivos
GET /privado/media/borrar/@id = Privado\Media->borrar
GET /privado/media/fijar/@id = Privado\Media->fijar_foto_perfil

;SUSCRIPCION
GET /privado/suscripcion/@action/@id = Privado\Suscripcion->@action
POST /privado/suscripcion/contratar = Privado\Suscripcion->contratar
POST /privado/suscripcion/guardar = Privado\Suscripcion->guardar

;CONTACTO
;GET /privado/contacto/@action = Privado\Inicio->pendiente


; ADMIN
GET /admin = Admin\Inicio->inicio
GET /admin/{@controller} = Admin\{@controller}->inicio
GET /admin/{@controller}/{@action} = Admin\{@controller}->{@action}


;API
GET /api/descuentos = Api->get_descuentos



